### ISSUE TITLE
Class canvas not working with variable Stage

### ISSUE THREAD

**Issue by carmof** [carmof/webPortifolio#12]
When I create the class Canvas with the variable "stage" (object that controls the canvas) the object is not working, when I use ".appendChild(x)" to it, it throws an error saying that the variable doesn't have this method. So, to fix it, I am passing the stage every time that I use any canvas method

ex: this.canvas.render(this.getState(), this.stage);

, and this is not what I want, I would like it to be just

this.canvas.render(this.getState());

Is there any way to make this class Canvas have the variable Stage and work properly ?

OBS: object canvas is created in game.js
this.canvas.render(this.getState(), this.stage);

**Comment by skiadas** [comment]
Looking at your canvas constructor, I am not seeing any place where the argument you pass to it is used, in fact you don't have a parameter specified in the definition (even though you call it with one). 

So when you do `base.canvas = Canvas.new(canvasObj);`, then as far as I can tell the `canvasObj` part is being ignored. Shouldn't you capture it to an instance variable? Seems to me your constructor should be taking a "stage" parameter, then store it in an instance variable, then you can access that variable wherever you are currently using the second argument.

**Comment by carmof** [comment]
Problem fixed. Thank you!
