### ISSUE TITLE
Problem using "easelJS"

### ISSUE THREAD

**Issue by carmof** [carmof/webPortifolio#9]
I am trying to "import" the easelJS through its address "https://code.createjs.com/easeljs-0.8.0.min", but the variable created with it is "undefined"

**Comment by skiadas** [comment]
Hm yeah, I see the problem. The file is accessed directly, but it is not created in a way that you can get a return value from it. Basically, it doesn't play nice with AMD.

So instead what you want to do is included it there as you did, but without a corresponding variable to grab that spot.

Instead you should find that a global variable called "createjs" has been created. It has a number of properties in it, and one of those is EaselJS. (`console.log("createjs")` should show you some of those).
